services:
  banzai_scan_server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    command: uvicorn mcp_servers.scan_server:app --host 0.0.0.0 --port 8000 --reload

  banzai_subdomain_server:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: uvicorn mcp_servers.subdomain_server:app --host 0.0.0.0 --port 8000 --reload

  banzai_dns_analysis_server:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    command: uvicorn mcp_servers.dns_analysis_server:app --host 0.0.0.0 --port 8000 --reload

  banzai_supabase_mcp:
    build: .
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    environment:
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    command: uvicorn mcp_servers.supabase_mcp_wrapper:app --host 0.0.0.0 --port 8003 --reload

  banzai_directory_fuzzer:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    command: python mcp_servers/directory_fuzzer_server.py

  banzai_cli:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    command: tail -f /dev/null  # Keep container running for CLI access 