services:
  banzai_scan_server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: python mcp_servers/port_scanner_api.py
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN

  banzai_subdomain_server:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: python mcp_servers/subdomain_api.py

  banzai_dns_analysis_server:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: python mcp_servers/dns_analysis_api.py

  banzai_supabase_mcp:
    build: .
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    command: python mcp_servers/supabase_api.py

  banzai_directory_fuzzer:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: python mcp_servers/directory_fuzzer_api.py 